Update js.phtml
Uncaught TypeError: $.ajax(...).success is not a function
    at loadoptions (edit/:753:14)
    at edit/:761:5
    at Object.execCb (require.js:1696:33)
    at Object.execCb (resolver.js:156:31)
    at Module.check (require.js:883:51)
    at Module.enable (require.js:1176:22)
    at Module.init (require.js:788:26)
    at require.js:1460:36